### ISSUE TITLE
BUG: "Quantitative Economics with Julia" header link is broken

### ISSUE THREAD

**Issue by jbrightuniverse** [QuantEcon/lecture-julia.myst#106] opened 2021-09-05 02:24 UTC
The URL attached to the `Quantitative Economics with Julia` hyperlink on the top of every page leads to a URL of the form:
`https://quantecon.github.io/lecture-julia.myst/name_of_the_current_file/intro.html`

As the homepage is located at `https://quantecon.github.io/lecture-julia.myst/intro.html` instead, the link breaks.

As far as I can tell, this may be a theme issue as this is automatically generated in each lecture page (rather than being specified in each lecture file).

@AakashGfude @mmcky

**Comment by jlperla** [comment] 2021-09-05 03:20
Thanks @jbrightuniverse  As I am not sure what the themes look like prior to being on the live site, let me put this in the 1.6 milesstone and then we can review as we prepare to go live.

**Comment by mmcky** [comment] 2021-09-06 00:00
@AakashGfude this project organises content with `folders`. It looks like the `folder` path is used when setting this to `home` location so it issues a 404. This isn't an issue on `datascience` as each folder has an index.html file so resolves to the main page for each folder (as a local home) it appears.

**Comment by AakashGfude** [comment] 2021-09-06 07:26
Thanks, guys for reporting this and analyzing it. Should be fixed in this PR: https://github.com/QuantEcon/quantecon-book-theme/pull/162

**Comment by jlperla** [comment] 2021-09-06 15:48
Sounds great. Do we need to bump any package versions, etc in this repo? Eg the https://github.com/QuantEcon/lecture-julia.myst/blob/main/requirements.txt

Or are we not quite ready for that.

**Comment by AakashGfude** [comment] 2021-09-06 22:50
@jlperla you are right. Need to bump `quantecon-book-theme` to the latest version. That is 0.2.7

**Comment by jlperla** [comment] 2021-09-06 22:58
@mmcky and @AakashGfude can I hand this deployment stuff off to you guys to take this to live? Not sure the exact changes for things like this, and how they interact with the devops

**Comment by mmcky** [comment] 2021-09-06 23:41
07bb32c updates the software and pins the new `quantecon-book-theme` to fix this. Will close the issue once fix is confirmed on current publish run.

**Comment by mmcky** [comment] 2021-09-07 00:50
This is fixed.

**Closed by mmcky** 2021-09-07 00:50 UTC
